services:
  flaresolverr:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    # DockerHub mirror vfhky/flaresolverr:latest
    image: ghcr.io/vfhky/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
