name: Clean Schedule

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  cleanup_runs:
    name: Cleanup Old Workflow Runs
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 5
          keep_minimum_runs: 5
